name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest Docker version
        id: get_version
        run: |
          # Get the latest release tag for Docker
          latest_version=$(curl -s https://api.github.com/repos/moby/moby/releases/latest | jq -r '.tag_name')
          # Extract numeric part of the version, if necessary
          latest_version=${latest_version#v}
          echo "Latest Docker version: $latest_version"
          echo "DOCKER_VERSION=$latest_version" >> $GITHUB_ENV

      - name: Build documentation with Writerside
        uses: JetBrains/writerside-github-action@v4
        env:
          INSTANCE: Writerside/hi
          ARTIFACT: webHelpHI2-all.zip
          DOCKER_VERSION: ${{ env.DOCKER_VERSION }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: webHelpHI2-all.zip

      - name: Deploy to GitHub Pages
        if: success()
        uses: actions/deploy-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build