name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # トリガーしたいブランチを指定

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build documentation with Writerside
        uses: JetBrains/writerside-github-action@v4
        env:
          INSTANCE: Writerside/hi  # モジュール名とインスタンスIDを指定
          ARTIFACT: webHelpHI2-all.zip  # ビルダーが生成するアーティファクト名
          DOCKER_VERSION: 241.18775  # 使用するWriterside Dockerビルダーのバージョン

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: webHelpHI2-all.zip

      - name: Deploy to GitHub Pages
        if: success()
        uses: actions/deploy-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # アーティファクトの展開ディレクトリ